/sub/rgb/topic:  '/camera/rgb/image_rect_color'
/sub/depth/topic: '/camera/depth_registered/sw_registered/image_rect'
/sub/points/topic: '/camera/depth_registered/points'
/usepoints: false
/buffernumber: 1000



/fx: 517.5
/fy: 516.5
/cx: 318.6 
/cy: 255.3
/width: 640
/height: 480



